services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1-password2
      MYSQL_DATABASE: sisoc-local
      MYSQL_TCP_PORT: 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/local-dump.sql:/docker-entrypoint-initdb.d/local-dump.sql
    ports:
      - 3308:3307
    expose:
      - 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3307"]
      interval: 10s
      timeout: 10s
      retries: 5

  django:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
      - "3000:3000" # Debugger
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/sisoc/

volumes:
  mysql_data:
